export DESIGN_NAME=SG13G2Top
export DESIGN_NICKNAME = elemrv_h
export PLATFORM=ihp-sg13g2

export SDC_FILE=${DESIGN_HOME}/${PLATFORM}/$(DESIGN_NICKNAME)/SG13G2Top.sdc
export VERILOG_FILES=${DESIGN_HOME}/${PLATFORM}/$(DESIGN_NICKNAME)/SG13G2Top.v

export SEAL_GDS = ${DESIGN_HOME}/${PLATFORM}/$(DESIGN_NICKNAME)//macros/sealring/sealring.gds.gz

export DIE_AREA = 0.0 0.0 2150.4 2150.82
export CORE_AREA = 394.08 396.9 1753.44 1753.92

export MAX_ROUTING_LAYER = TopMetal2
export HAS_IO_RING = 1

export TNS_END_PERCENT = 100
export PLACE_DENSITY = 0.75

export FOOTPRINT_TCL = ${DESIGN_HOME}/${PLATFORM}/$(DESIGN_NICKNAME)/SG13G2Top.pad.tcl
export PDN_TCL = ${DESIGN_HOME}/${PLATFORM}/$(DESIGN_NICKNAME)/SG13G2Top.pdn.tcl
